# Generated by Django 5.2.13 on 2026-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_covers/"
            ),
        ),
    ]
