# Generated by Django 5.2.13 on 2026-04-22 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas')], default='electricity', max_length=20)),
                ('period_month', models.DateField(help_text='First of the month this reading is for')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_photo_url', models.URLField(blank=True)),
                ('ocr_extracted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted by Tenant'), ('confirmed', 'Confirmed by Landlord'), ('disputed', 'Disputed'), ('locked', 'Locked (billed)')], default='submitted', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_readings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_readings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='properties.unit')),
            ],
            options={
                'db_table': 'meter_readings',
                'indexes': [models.Index(fields=['organization', 'status'], name='meter_readi_organiz_aa0874_idx'), models.Index(fields=['unit', 'period_month'], name='meter_readi_unit_id_21cd8b_idx')],
                'unique_together': {('unit', 'meter_type', 'period_month')},
            },
        ),
    ]
