# Generated by Django 5.2.13 on 2026-04-22 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('billing', '0002_setup_q_schedules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('gateway', 'Online Gateway')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gateway', models.CharField(blank=True, help_text='razorpay, stripe, etc.', max_length=30)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['organization', 'status'], name='payments_organiz_6f226c_idx'), models.Index(fields=['bill', 'status'], name='payments_bill_id_2ad6b0_idx'), models.Index(fields=['-paid_at'], name='payments_paid_at_7415d9_idx')],
            },
        ),
    ]
